version: "3.3"

services:

  whoami:
    image: "traefik:v2.0"
    container_name: "whoami"
    links:
      - whoami-service
    command:
      #- "--log.level=DEBUG"
      - "--providers.file.filename=/tmp/whoami.yaml"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:8080"
      - "--entryPoints.traefik.address=:8081"
      - "--ping=true"
      - "--log=true"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "18080:8080"
      - "18081:8081"
    volumes:
      - "./whoami.yaml:/tmp/whoami.yaml:ro"

  whoami-service:
    image: "containous/whoami"
    container_name: "whoami-service"

  auth:
    image: "traefik:v2.0"
    container_name: "auth"
    links:
      - auth-service
    command:
      #- "--log.level=DEBUG"
      - "--providers.file.filename=/tmp/auth.yaml"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:8080"
      - "--entryPoints.traefik.address=:8081"
      - "--ping=true"
      - "--log=true"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "28080:8080"
      - "28081:8081"
    volumes:
      - "./auth.yaml:/tmp/auth.yaml:ro"
  auth-service:
    build: ./auth
    container_name: "auth-service"
