version: "3.3"

services:

  traefik:
    image: "traefik:v2.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
      - "--entrypoints.traefik.address=:8081"
      - "--ping=true"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.middlewares.test-inflightreq.inflightreq.amount=80"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=50"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.sourcecriterion.requestheadername=X-Auth-User"
      - "traefik.http.middlewares.test-limit.buffering.maxRequestBodyBytes=20000"
      - "traefik.http.middlewares.test-limit.buffering.memRequestBodyBytes=8000"
      - "traefik.http.middlewares.test-auth.forwardauth.address=http://auth:3000/"
      - "traefik.http.middlewares.test-auth.forwardauth.authResponseHeaders=X-Auth-User, X-Secret"
      - "traefik.http.middlewares.test-header.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.test-header.headers.accessControlAllowOrigin=*"
      - "traefik.http.middlewares.test-header.headers.accessControlAllowHeaders=authorization,content-type,accept,x-next-page"
      - "traefik.http.middlewares.test-header.headers.accessControlExposeHeaders=x-page,x-count,x-total,x-limit,x-to,x-from"
      - "traefik.http.middlewares.test-header.headers.accessControlMaxAge=0"
      - "traefik.http.middlewares.test-header.headers.addVaryHeader=true"
      - "traefik.http.middlewares.test-retry.retry.attempts=4"
      - "traefik.http.middlewares.test-compress.compress=true"
      - "traefik.http.routers.whoami.middlewares=test-header@docker,test-inflightreq@docker,test-limit@docker,test-auth@docker,test-ratelimit@docker,test-retry@docker,test-compress@docker"
  auth:
    build: ./auth
    container_name: "auth-simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.auth-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.auth-ratelimit.ratelimit.burst=50"
      - "traefik.http.routers.auth.middlewares=auth-ratelimit@docker"

